name: install-and-test-workflow
env:
  UV_SYSTEM_PYTHON: true
on: [push]
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{matrix.python_version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Install dependencies
        run: |
          uv pip install '.[dev]' 
          uv pip install coverage coveralls
      - name: Test with pytest
        run: |
          python -m coverage run -m pytest -sv
      - name: Submit to coveralls
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github

  ruff-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: "check ."
  # to enable auto-formatting check, uncomment the following lines below
  # ruff-formatting:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: chartboost/ruff-action@v1
  #       with:
  #         args: "format . --check"
